version: '3.8'

networks:
  babunet:

volumes:
  postgres-data:
    name: user-api_postgres-${RAILS_ENV:-development}
    driver: local

services:
  postgres:
    image: postgres
    container_name: user-api_postgres-${RAILS_ENV:-development}
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    # ports:
    #   - "5432:5432"
    networks:
      - babunet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  
  rails:
    container_name: user-api_rails-${RAILS_ENV:-development}
    # entrypoint: ./entrypoint.sh # @override
    build:
      context: .
      target: ${RAILS_ENV:-development}
    tty: true
    environment: #! this variables will @override .env
      RAILS_ENV: ${RAILS_ENV:-development}
      PORT: ${RAILS_PORT:-3000} # @override for puma.rb, entrypoint.sh
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-test.private.babunet} # @override config.hosts
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    ports:
      - "${RAILS_PORT:-3000}:${RAILS_PORT:-3000}"
    networks:
      - babunet
    depends_on:
      - postgres
    volumes:
      - .:/home/rails/user-api
    restart: unless-stopped
