default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: user-api-development
  username: postgres
  password: mysecurepass
  host: postgres
  port: 5432

test:
  <<: *default
  username: postgres
  password: mysecurepass
  host: postgres
  port: 5432
  database: user-api-test

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>
  host: <%= ENV.fetch("DATABASE_URL") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>
